services:
  - type: web
    name: codesnap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python create_db.py && gunicorn app:app
    envVars:
      - key: DATABASE_URL
        placeholder: "Enter your Neon.tech connection string here"
      - key: SECRET_KEY
        generateValue: true